Postgres tests
logos-messaging/logos-delivery-go pull request #760
Opened 2023-09-21 04:03 UTC by harsh-98

# Description
- Change test that are using sqlite to use postgres. Related to https://github.com/waku-org/go-waku/issues/607

# Changes

- [x] Limit can't be negative for queries in postgres.
- [x] Change store test to use postgres.
- [x] Fixature for testing postgres/sqlite store test. 
- [x] Add postgres module tests.
- [x] Based on driverType, NewQueries from sqlite/postgres should be used in waku_node.  

# Tests

2023-09-21 04:05 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | c01ca928 | [#1](https://ci.status.im/job/go-waku/job/prs/job/linux/job/PR-760/1/) | 2023-09-21 04:05:21 | ~1 min | `linux` | [:page_facing_up:`log`](https://ci.status.im/job/go-waku/job/prs/job/linux/job/PR-760/1/consoleText) |

2023-09-21 06:54 UTC, jakubgs commented
Fixed.

2023-09-26 00:06 UTC, richard-ramos requested changes

2023-09-26 00:06 UTC, richard-ramos commented on waku/persistence/store.go
> +		sqlStmt := `DELETE FROM message WHERE id IN (SELECT id FROM message ORDER BY receiverTimestamp DESC OFFSET $1)`
This does not work in SQLite. The LIMIT keyword is required when specifying an OFFSET.   If postgresql does not allow negative limits, then we need to extract this query, similar to how it was done with CreateTable in here https://github.com/waku-org/go-waku/blob/16ec22596ef3e4b1a65af1ea1f2a0429847c9f7a/waku/persistence/postgres/postgres.go#L59-L66 which has db specific implementations

2023-10-03 20:37 UTC, richard-ramos commented on waku/persistence/store.go
> +		sqlStmt := `DELETE FROM message WHERE id IN (SELECT id FROM message ORDER BY receiverTimestamp DESC OFFSET $1)`
This sounds like a bug!

2023-10-04 14:30 UTC, jakubgs commented on ci/Jenkinsfile.tests
> +    DB_CONT  = "status-go-test-db-${env.EXECUTOR_NUMBER.toInteger() + 1}"
Why is this calling the container `status-go-test-db-...`? Pretty sure this isn't `status-go` repo.

2023-10-04 14:31 UTC, jakubgs commented on ci/Jenkinsfile.tests
> +    stage('postgres tests') {
The whole Jenkinsfile is for tests, and the job is called `tests`. I don't think yet another `tests` in the stage names. Just call the stage `PostgreSQL`.

2023-10-05 06:56 UTC, jakubgs commented on waku/persistence/postgres/mock.go
> +var dbUrlTemplate = "postgres://harshjain@localhost:%s/%s?sslmode=disable"
Pretty sure you don't want to leave this like this. Also, shouldn't the host and the user be also templateable?

2023-10-05 06:56 UTC, jakubgs approved these changes
Mostly looks fine.

2023-10-12 18:36 UTC, richard-ramos approved these changes
Very cool. 
if you decide to Squash & Merge the PR, do remember to change the name to match the format (something like `feat: postgresql tests`), or just use rebase & merge since the individual commit messages are fine :)

2023-10-13 03:35 UTC, merged